name: posydon_conda
channels:
  - posydon
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiofiles=22.1.0=pyhd8ed1ab_0
  - aiosqlite=0.20.0=pyhd8ed1ab_0
  - anyio=3.5.0=py37h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h7f8727e_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - astropy=4.0.1.post1=py37h8f50634_0
  - atk=2.36.0=ha770c72_4
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=22.1.0=py37h06a4308_0
  - babel=2.11.0=py37h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - blas=1.1=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.5=hc2324a3_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.12.31=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h18b612c_1001
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.0=py37h7f8727e_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - configparser=5.0.0=py_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=hfdff14a_1
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37h06a4308_0
  - expat=2.6.4=h5888daf_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.38.0=py37h540881e_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.2=h19a9c64_1
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.66.3=h58526e2_0
  - gobject-introspection=1.66.1=py37h9019ea4_3
  - graphite2=1.3.13=h59595ed_1003
  - gstreamer=1.14.5=h36ae1b5_2
  - gtk2=2.24.32=h90f3771_0
  - h5py=3.3.0=nompi_py37ha3df211_100
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=58.2=hf484d3e_1000
  - idna=3.4=py37h06a4308_0
  - iminuit=1.4.9=py37h0da4684_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.15.2=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_2
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.18.1=py37h06a4308_1
  - jinja2=3.1.2=py37h06a4308_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.17.3=py37h06a4308_0
  - jsonschema-with-format-nongpl=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py37h06a4308_8
  - jupyter_client=7.4.9=py37h06a4308_0
  - jupyter_console=6.4.4=py37h06a4308_0
  - jupyter_core=4.11.2=py37h06a4308_0
  - jupyter_events=0.6.3=pyhd8ed1ab_1
  - jupyter_server=1.23.4=py37h06a4308_0
  - jupyter_server_fileid=0.9.2=pyhd8ed1ab_0
  - jupyter_server_ydoc=0.8.0=pyhd8ed1ab_0
  - jupyter_ydoc=0.2.4=pyhd8ed1ab_0
  - jupyterlab=3.6.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py37h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.4=py37h7cecad7_0
  - lcms2=2.12=hddcbb42_0
  - lerc=3.0=h9c3ff4c_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=26_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=26_linux64_openblas
  - libdeflate=1.10=h7f98852_0
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.66.3=hbe7bbb4_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=26_linux64_openblas
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.3.0=h0fcbabc_4
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.9.9=h13577e0_2
  - libxslt=1.1.33=h7d1a2b0_0
  - libzlib=1.2.13=h4ab18f5_6
  - lxml=4.5.1=py37hefd8a0e_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib=3.5.0=py37h89c1867_0
  - matplotlib-base=3.5.0=py37h1058ff1_0
  - matplotlib-inline=0.1.6=py37h06a4308_0
  - matplotlib-label-lines=0.5.1=pyhd8ed1ab_0
  - mistune=0.8.4=py37h14c3975_1001
  - mock=5.1.0=pyhd8ed1ab_0
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py37hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.5.2=py37h06a4308_0
  - nbclient=0.5.13=py37h06a4308_0
  - nbconvert=6.5.4=py37h06a4308_0
  - nbformat=5.7.0=py37h06a4308_0
  - ncurses=6.5=h2d0b736_2
  - nest-asyncio=1.5.6=py37h06a4308_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.5.2=py37h06a4308_0
  - notebook-shim=0.2.2=py37h06a4308_0
  - numexpr=2.8.3=py37h85a3170_100
  - numpy=1.19.5=py37h3e96413_3
  - olefile=0.47=pyhd8ed1ab_0
  - openblas=0.3.28=pthreads_h6ec200e_0
  - openjpeg=2.5.0=h7d73246_0
  - openssl=1.0.2u=h7b6447c_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.3.0=py37h219a48f_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.42.4=h7062337_4
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py37h0f21c89_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.38.0=h516909a_1003
  - pkgutil-resolve-name=1.3.10=py37h06a4308_0
  - posydon=1.0.4=py_0
  - progressbar2=4.0.0=pyhd8ed1ab_0
  - prometheus_client=0.14.1=py37h06a4308_0
  - prompt-toolkit=3.0.36=py37h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.6.7=py37h516909a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.6.0=py37h13b7fb3_1008
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37_1
  - pytables=3.6.1=py37h0c4f3e0_3
  - python=3.7.0=hd21baee_1006
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=py37h06a4308_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-utils=3.5.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0=py37h540881e_4
  - pyzmq=23.2.0=py37h6a678d5_0
  - qt=5.6.2=hce4f676_1013
  - qtconsole=5.4.0=py37h06a4308_0
  - qtpy=2.2.0=py37h06a4308_0
  - readline=7.0=hf8c457e_1001
  - requests=2.28.1=py37h06a4308_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.5.2=py37habc2bb6_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=59.8.0=py37h89c1867_1
  - sip=4.18.1=py37hf484d3e_1000
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.2.0=py37h06a4308_1
  - soupsieve=2.3.2.post1=py37h06a4308_0
  - sqlite=3.28.0=h8b20d00_0
  - terminado=0.17.1=py37h06a4308_0
  - tinycss2=1.2.1=py37h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py37h06a4308_0
  - tornado=6.2=py37h540881e_0
  - tqdm=4.48.2=pyh9f0ad1d_0
  - traitlets=5.7.1=py37h06a4308_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - unicodedata2=14.0.0=py37h540881e_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.14=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37h06a4308_4
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py37h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - y-py=0.5.4=py37hbd0741f_0
  - yaml=0.2.5=h7f98852_2
  - ypy-websocket=0.8.2=pyhd8ed1ab_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/alangu/anaconda3/envs/posydon_conda
